export const ITEMS = [
  {
    id: 2,
    itemName: 'first item',
    color: 'silver',
    dateTime: '2022-10-09T18:30:00.000Z',
    description: 'hehe',
    brand: 'idkk',
    city: 'in',
    category: '1',
    userId: 1,
    isFounded: 1,
    college: null,
    createdAt: '2022-08-01T23:26:35.000Z',
    thumbnail: 'https://picsum.photos/200/300?random=4',
  },
  {
    id: 3,
    itemName: 'second item',
    color: 'red',
    dateTime: '2022-10-09T18:30:00.000Z',
    description: 'this is sdjnjnjaqedcfoejwioen',
    brand: 'idkk',
    city: 'in',
    category: '3',
    userId: 1,
    isFounded: 1,
    college: null,
    createdAt: '2022-08-03T23:26:35.000Z',
    thumbnail: 'https://picsum.photos/200/300?random=1',
  },
  {
    id: 5,
    itemName: 'Third item',
    color: 'lime',
    dateTime: '2022-10-09T18:30:00.000Z',
    description: 'this is sdjnjnjaqedcfoejwioen',
    brand: 'idkk',
    city: 'in',
    category: '2',
    userId: 3,
    isFounded: 1,
    college: null,
    createdAt: '2022-07-31T23:26:35.000Z',
    thumbnail: 'https://picsum.photos/200/300?random=1',
  },
  {
    id: 6,
    itemName: 'Fourth item',
    color: 'blue',
    dateTime: '2022-10-09T18:30:00.000Z',
    description: 'this is rre',
    brand: 'grdgerg',
    city: 'ss',
    category: '10',
    userId: 3,
    isFounded: 0,
    college: null,
    createdAt: '2022-08-08T23:26:35.000Z',
    thumbnail: 'https://picsum.photos/200/300?random=1',
  },
  {
    id: 7,
    itemName: 'tnew sse',
    color: 'red',
    dateTime: '2022-10-09T18:30:00.000Z',
    description: 'thiaaas is sdjnjnjaqedcfoejwioen',
    brand: 'youknow',
    city: 'in',
    category: 'tom',
    userId: 3,
    isFounded: 1,
    college: null,
    createdAt: '2022-08-21T19:05:15.000Z',
    thumbnail: 'https://picsum.photos/200/300?random=2',
  },
];
const dummyData = [
  {
    id: 1,
    itemName: 'Black Leather Wallet',
    color: 'black',
    dateTime: '2022-12-01T12:00:00',
    brand: 'Louis Vuitton',
    city: 'New York',
    category: 'Accessories',
    isFound: false,
    thumbnail: 'https://example.com/wallet1.jpg',
  },
  {
    id: 2,
    itemName: 'Silver iPhone X',
    color: 'silver',
    dateTime: '2022-11-25T18:00:00',
    brand: 'Apple',
    city: 'Los Angeles',
    category: 'Electronics',
    isFound: false,
    thumbnail: 'https://example.com/iphone2.jpg',
  },
  {
    id: 3,
    itemName: 'Red Backpack',
    color: 'red',
    dateTime: '2022-11-22T09:00:00',
    brand: 'North Face',
    city: 'Chicago',
    category: 'Accessories',
    isFound: false,
    thumbnail: 'https://example.com/backpack3.jpg',
  },
  {
    id: 4,
    itemName: 'Gold Necklace',
    color: 'gold',
    dateTime: '2022-11-20T14:00:00',
    brand: 'Tiffany & Co.',
    city: 'Houston',
    category: 'Jewelry',
    isFound: false,
    thumbnail: 'https://example.com/necklace4.jpg',
  },
  {
    id: 5,
    itemName: 'Blue Baseball Cap',
    color: 'blue',
    dateTime: '2022-11-19T16:00:00',
    brand: 'Nike',
    city: 'Philadelphia',
    category: 'Accessories',
    isFound: false,
    thumbnail: 'https://example.com/baseballcap5.jpg',
  },
  {
    id: 6,
    itemName: 'Green Sunglasses',
    color: 'green',
    dateTime: '2022-11-18T10:00:00',
    brand: 'Ray-Ban',
    city: 'Phoenix',
    category: 'Accessories',
    isFound: false,
    thumbnail: 'https://example.com/sunglasses6.jpg',
  },
  {
    id: 7,
    itemName: 'Purple Handbag',
    color: 'purple',
    dateTime: '2022-11-17T11:00:00',
    brand: 'Coach',
    city: 'San Antonio',
    category: 'Accessories',
    isFound: false,
    thumbnail: 'https://example.com/handbag7.jpg',
  },
];
