name: Run Tests

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm ci  # Use npm ci for faster and consistent dependency installation

      - name: Run tests
        run: npm test  # Modify this command if your test command is different
